// Hard-reject disposable / throwaway email providers at signup.
//
// A curated list of ~120 domains that real Nagars never use, but low-effort
// abusers reach for routinely (mailinator, 10minutemail, yopmail, etc.). Kept
// deliberately narrow — we'd rather miss an obscure throwaway than wrongly
// reject a genuine member's quirky personal domain. Imported on both client
// (for immediate UX feedback on /join) and server (the real enforcement
// boundary).
//
// To grow: add domains here. To remove: someone's complained about being
// wrongly rejected — pull the domain out, don't add an allowlist.

const DISPOSABLE_DOMAINS = new Set<string>([
  "0815.ru",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemailbox.com",
  "20minutemail.com",
  "30minutemail.com",
  "anonbox.net",
  "anonymbox.com",
  "burnermail.io",
  "byom.de",
  "deadaddress.com",
  "deagot.com",
  "despam.it",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dodgit.com",
  "drdrb.net",
  "dropmail.me",
  "duck2.club",
  "e4ward.com",
  "easytrashmail.com",
  "einrot.com",
  "einrot.de",
  "email-temp.com",
  "emaildrop.io",
  "emailfake.com",
  "emailisvalid.com",
  "emailondeck.com",
  "emailtemporanea.net",
  "emkei.cf",
  "fakeinbox.com",
  "fakemail.fr",
  "fakemail.net",
  "filzmail.com",
  "fudgerub.com",
  "getairmail.com",
  "getnada.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "hidemail.de",
  "huyfp.com",
  "imgof.com",
  "inboxbear.com",
  "inboxkitten.com",
  "inboxproxy.com",
  "incognitomail.com",
  "inboxalias.com",
  "instant-mail.de",
  "jetable.org",
  "jourrapide.com",
  "kasmail.com",
  "klzlk.com",
  "letthemeatspam.com",
  "mail-temp.com",
  "mail-temporaire.fr",
  "mail-temporaire.com",
  "mail.tm",
  "mail7.io",
  "mailbox.in.ua",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailmoat.com",
  "mailnesia.com",
  "mailnull.com",
  "mailtemp.info",
  "mailtemp.net",
  "mailtothis.com",
  "maildax.com",
  "meltmail.com",
  "mintemail.com",
  "moakt.com",
  "mohmal.com",
  "monumentmail.com",
  "mytemp.email",
  "mytrashmail.com",
  "nada.email",
  "nada.ltd",
  "neverbox.com",
  "no-spam.ws",
  "nowmymail.com",
  "objectmail.com",
  "owlymail.com",
  "pokemail.net",
  "proxymail.eu",
  "rcpt.at",
  "rhyta.com",
  "rmqkr.net",
  "sharklasers.com",
  "shitmail.me",
  "shortmail.net",
  "sneakemail.com",
  "spam4.me",
  "spambog.com",
  "spambox.us",
  "spamgourmet.com",
  "spamherelots.com",
  "spaminator.de",
  "spamoff.de",
  "spamthis.co.uk",
  "speed.1s.fr",
  "superrito.com",
  "tafmail.com",
  "teleworm.com",
  "teleworm.us",
  "tempail.com",
  "tempemail.com",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.email",
  "tempmail.net",
  "tempmail.us",
  "tempmail2.com",
  "tempmailer.com",
  "tempmailo.com",
  "temp-mail.io",
  "temp-mail.org",
  "tempr.email",
  "throwam.com",
  "throwawaymail.com",
  "tmail.ws",
  "tmailinator.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trashinbox.com",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.ws",
  "trashymail.com",
  "tyldd.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yourtempmail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "whatpda.com",
  "zoaxe.com",
  "zoemail.org",
]);

// Returns true when the address is well-formed AND the domain is on the
// blocklist. Malformed addresses return false (a separate regex catches those).
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
